Sidekiq directly
andycroll/andycroll.com pull request #140
Opened 2021-09-29 15:10 UTC by andycroll

2021-10-02 09:09 UTC, nodunayo requested changes, later dismissed
This piece feels like it's lacking in flow. Feels like a bunch of random points put one after the other, and the paragraphs aren't always clear/easy to read.

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +If you build a web application you should minimize the amount of time spent responding to every user; a fast website means a happy user. One way of doing that is to run long-running, parallelisable,
Oxford comma after 'calculations', please!

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +[Active Job](https://guides.rubyonrails.org/active_job_basics.html) is the recommended way of enqueuing and running background work in Rails. It provides a wrapper around a bunch of [different implem
*its own

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +One of the most popular, battle-tested and performant asynchronous frameworks is [Sidekiq](https://sidekiq.org), which is multi-threaded and utilises Redis for it's queuing storage. It’s an open sour
Oxford comma in the first list, please!

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +One of the most popular, battle-tested and performant asynchronous frameworks is [Sidekiq](https://sidekiq.org), which is multi-threaded and utilises Redis for it's queuing storage. It’s an open sour
*its

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +Disclaimer: I'm a massive fan and “Pro” customer of Sidekiq and have met [Mike](https://twitter.com/getajobmike) (it's author) a little at a couple of Ruby conferences. That hasn't coloured my view o
*_its_ author...

*remove 'a little' before 'at a couple...'

*Full stop after 'view of the library.

*worth every penny given how we use it at work

(Maybe this disclaimer should go at the end??)

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +Active Job is a solid super-set of Sidekiq's functionality, but you’re missing out on a number of advantages if you use it without.
*superset ?

*if you don't use Sidekiq directly

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +If you're doing _a lot_ of work in the background, enqueuing many small fast-running jobs (as is generally suggested) there is a [2—20x performance improvement](https://github.com/mperham/sidekiq/wik
*comma needed after closing parenthesis 

*The level of improvement will be dependant...

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +If you are enqueing lots of jobs, you could be using [Sidekiq’s bulk enqueing functionality](https://github.com/mperham/sidekiq/wiki/Bulk-Queueing), this is hard to do performantly when using sidekiq
Full stop after closing parentheses.

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +If you are enqueing lots of jobs, you could be using [Sidekiq’s bulk enqueing functionality](https://github.com/mperham/sidekiq/wiki/Bulk-Queueing), this is hard to do performantly when using sidekiq
Capitalise Sidekiq.

And decide if you're saying 'Active Job' with a space or not.

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +When using Sidekiq via Active Job there are, confusingly, multiple levels of retries in the event of a job failure. Active Job has it's own retry mechanism, which once completed then passes down to S
*its

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +When using Active Job and passing in an Active Record object, you rely on the object being serialized to a text argument using [Global ID](https://github.com/rails/globalid). This does save doing the
*from

This paragraph doesn't flow well.

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +There’s no real harm to “locking yourself into” a specific job framework. You are unlikely to swap in future for another queuing system with similar (intentionally) limited functionality availible in
I think quotes should only be around "locking"

*You are unlikely to switch to another queuing system...

End of this paragraph feels messy/out of place.

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +If you're using Sidekiq in prduction you should buy a license for the Pro version. The [extra reliability](https://github.com/mperham/sidekiq/wiki/Reliability#using-super_fetch) so that jobs are not
*production

Seems like there are extra spaces in between 'so that jobs are not lost'

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +When using Sidekiq directly you have to think more about your job arguments and perform object lookups yourself, Sidekiq only permits simple values as job arguments.
Full stop before Sidekiq.

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +You can use Active Job-style _and_ direct Sidekiq jobs onto the same queues at the same time because Active Job wraps Sidekiq. You don't have to switch everything, you can use both styles in the same
Messy paragraph.

2021-10-02 09:09 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +[Good Job](https://github.com/bensheldon/good_job) and [Que](https://github.com/que-rb/que) (postgres only) or [Delayed Job](https://github.com/collectiveidea/delayed_job) (any SQL database) are well
After the parentheses, start a new sentence: If you use one of these, you then don't need to run...

2021-10-03 06:44 UTC, nodunayo submitted a review, later dismissed

2021-10-03 06:44 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +You’re missing out on a number of advantages that you gain when you use Sidekiq directly.
```suggestion
You’re missing out on a number of advantages when you don't use Sidekiq directly.
```

2021-10-03 06:44 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +If you're doing _a lot_ of work in the background, enqueuing many small fast-running jobs—as is generally suggested—there is a [2—20x performance improvement](https://github.com/mperham/sidekiq/wiki/
*leads to a 2-20x perf..

2021-10-03 06:44 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +If you are enqueing lots of jobs, you could be using [Sidekiq’s bulk enqueing functionality](https://github.com/mperham/sidekiq/wiki/Bulk-Queueing), this is hard to do performantly when using Sidekiq
```suggestion
If you are enqueing lots of jobs, you could use [Sidekiq’s bulk enqueing functionality](https://github.com/mperham/sidekiq/wiki/Bulk-Queueing). This is hard to do performantly when using Sidekiq with Active Job.
```

2021-10-03 06:44 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +There are, confusingly, multiple levels of retries in the event of a job failure. Active Job has its own retry mechanism, which once completed then passes down to Sidekiq’s own (seperate and differen
Maybe take out the first 'confusingly' or change the last one to "tricky" or "difficult" or something like that.

2021-10-03 06:44 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +Active Job allows passing in an Active Record object to the `#perform` method, which is then serialized to a text argument using [Global ID](https://github.com/rails/globalid). This saves doing the l
*from

2021-10-03 06:44 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +There’s no real harm to “locking yourself into” a specific job framework. You are unlikely to swap to another queuing system with similarly limited Active Job functionality. When you consider replaci
This paragraph could be a little clearer. The first part, I think you need to make it clearer that you're trying to say: if using Sidekiq directly, don't worry about locking yourself into something specific.

The second part: are you saying that if you're replacing your *_asynchronous_ (sp) infrastructure, then you should be considering a migration then regardless?

2021-10-03 06:44 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +When using Sidekiq directly you have to think more about your job arguments and perform object lookups yourself. Sidekiq only permits simple values as job arguments.
```suggestion
When using Sidekiq directly you have to think more about what your job arguments should be and then perform object lookups yourself. Sidekiq only permits simple values as job arguments.
```

2021-10-03 06:44 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +You can define and use Active Job-style _and_ direct Sidekiq jobs at the same time. You don't have to switch, you can use both styles in the same application.
Why is this part of "Why not"?

*You don't have to use one or the other. Both styles can be used in the same application.

(Is this recommended?)

2021-10-03 06:44 UTC, nodunayo commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +There is a deeper question as to why use Sidekiq at all if your workload is light, or you are early on in your project.
Maybe rephrase this to say something like: if your workload is like or you're early on in your project, perhaps you can start with AJ/you don't need to worry about setting up Sidekiq.

2021-10-03 09:53 UTC, andycroll commented on _posts/2021/2021-10-04-use-sidekiq-directly-not-through-active-job.md
> +If your workload is light, or you are early on in your project, you might not need Sidekiq (at least its Redis dependancy) at all.
```suggestion
If your workload is light, or you are early on in your project, you might not need Sidekiq (or at least its Redis dependancy) at all.
```

2021-10-03 14:06 UTC, merged