beware of raw in erb
andycroll/andycroll.com pull request #186
Opened 2023-07-11 17:55 UTC by andycroll

- first pass at raw erb <%==
- extra words

2023-07-11 20:01 UTC, nodunayo requested changes, later dismissed

2023-07-11 20:01 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +Rails automatically escapes HTML entities when rendering user input within HTML templates by default then uses a special class called `ActiveSupport::SafeBuffer` to handle string concatenation and re
```suggestion
Rails automatically escapes HTML entities when rendering user input within HTML templates by default, and then uses a special class called `ActiveSupport::SafeBuffer` to handle string concatenation and the final rendering of the user-generated content. `SafeBuffer` is designed to prevent inadvertent double-escaping of the string or bypassing of encoding mechanisms.
```

2023-07-11 20:01 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +…Rails’ sanitization methods to ensure content is sanitized before it gets to the view:
*Rails's — the grammatically correct way is to have a trailing "apostrophe 's'" unless the word represents a plural!

2023-07-11 20:01 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +…Rails’ sanitization methods to ensure content is sanitized before it gets to the view:
Re "santization/sanitized" — I know the methods are spelt that way, but technically you're using it in a UK English piece of text...but yeah, this is very minor and probably best to just keep it with the 'z's.

2023-07-11 20:01 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +This is primarily about defending your application against malicious user input. Using the `<%== something %>` ERB tags in a Rails view template is the same as writing `<%= raw(something) %>` which c
* `SafeBuffer`

2023-07-11 20:01 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +As the [docs for `html_safe`](http://api.rubyonrails.org/classes/String.html#method-i-html_safe) say “It should never be called on user input”. You should let Rails do what it is good at.
Hmmmmmmm......I might have a couple things to review...

2023-07-11 20:01 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +The [`pagy` gem](https://github.com/ddnexus/pagy) recommends using the raw syntax `<%== pagy_nav(@pagy) if @pagy.pages > 1 %>`. This is safe to use because the output of the `pagy_nav` is handled by
```suggestion
The [`pagy` gem](https://github.com/ddnexus/pagy) recommends using the raw syntax `<%== pagy_nav(@pagy) if @pagy.pages > 1 %>`. This is safe to use because the output of `pagy_nav` is handled by the gem and there's very little risk of XSS as a result.
```

2023-07-11 20:01 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +The two reasons you might see this.
```suggestion
The are two reasons where you might see this:
```

Right?

2023-07-11 20:01 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +One is for performance, because there is a small overhead to managing the sanitization of each of the strings, but if you have a large amount of text you might see a performance benefit from avoiding
This paragraph/sentence needs tidying up!

Maybe: One is for performance. There is a small overhead...

2023-07-11 20:01 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +The _other_ is where managing the escaping of complicated strings is tricky, but that is _precisely_ where you need to do the work to properly manage potentially treacherous input yourself, or let th
Why is "other" emphasised?

2023-07-13 17:18 UTC, andycroll commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +This is primarily about defending your application against malicious user input. Using the `<%== something %>` ERB tags in a Rails view template is the same as writing `<%= raw(something) %>` which c
```suggestion
This is primarily about defending your application against malicious user input. Using the `<%== something %>` ERB tags in a Rails view template is the same as writing `<%= raw(something) %>` which completely avoids the protections offered by `SafeBuffer`.
```

2023-07-13 17:18 UTC, andycroll commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +…Rails’ sanitization methods to ensure content is sanitized before it gets to the view:
```suggestion
…Rails’s sanitization methods to ensure content is made safe before it gets to the view:
```

2023-07-13 17:20 UTC, andycroll commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +The _other_ is where managing the escaping of complicated strings is tricky, but that is _precisely_ where you need to do the work to properly manage potentially treacherous input yourself, or let th
```suggestion
The other is where managing the escaping of complicated strings is tricky, but that is _precisely_ where you need to do the work to properly manage potentially treacherous input yourself, or let the framework take the strain.
```

2023-07-13 17:21 UTC, andycroll commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +One is for performance, because there is a small overhead to managing the sanitization of each of the strings, but if you have a large amount of text you might see a performance benefit from avoiding
```suggestion
One is for performance. There is a small overhead to managing the sanitization of each of the strings. If you have a large amount or very long strings you _may_ see a performance improvement by avoiding the escaping.
```

2023-07-14 10:56 UTC, nodunayo requested changes, later dismissed

2023-07-14 10:56 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +This is primarily about defending your application against malicious user input. Using the `<%== something %>` ERB tags in a Rails view template is the same as writing `<%= raw(something) %>` which c
comma before "which"

2023-07-14 10:56 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +If you see `<%==` or `<% raw` in your ERB, consider it a bad smell. You should carefully evaluate the context, the source of the data, and the potential security risks before deciding to bypass HTML
Did you do this Oxford comma on your lonesome??

2023-07-14 10:56 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +If you look inside [ActiveSupport::SafeBuffer](https://api.rubyonrails.org/classes/ActiveSupport/SafeBuffer.html) you’ll see methods like `html_safe?` which are the methods Rails uses to manage the s
```suggestion
If you look inside [ActiveSupport::SafeBuffer](https://api.rubyonrails.org/classes/ActiveSupport/SafeBuffer.html), you’ll see methods like `html_safe?`, which are the methods Rails uses to manage the safety of user input that you're displaying in the browser.
```

2023-07-14 10:56 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +The are two reasons where you might see this:
```suggestion
The are two other cases where using unescaped HTML is okay:
```

2023-07-14 10:56 UTC, nodunayo commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +One is for performance. There is a small overhead to managing the sanitization of each of the strings. If you have a large amount or very long strings you _may_ see a performance improvement by avoid
```suggestion
One is for performance. There is a small overhead to managing the sanitization of each string. If you have a large amount or very long strings you _may_ see a performance improvement by avoiding the escaping.
```

2023-07-14 14:51 UTC, andycroll commented on _posts/2023/2023-07-17-beware-of-raw-erb.md
> +This is primarily about defending your application against malicious user input. Using the `<%== something %>` ERB tags in a Rails view template is the same as writing `<%= raw(something) %>` which c
```suggestion
This is primarily about defending your application against malicious user input. Using the `<%== something %>` ERB tags in a Rails view template is the same as writing `<%= raw(something) %>`, which completely avoids the protections offered by `SafeBuffer`.
```

2023-07-14 15:02 UTC, merged