optimise images
andycroll/andycroll.com pull request #206
Opened 2024-05-26 14:01 UTC by andycroll

2024-05-26 14:03 UTC, andycroll commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Smaller images mean faster downloads for your users. This is a lovely "set and forget" tool from the lovely folks at [Calibre](https://calibreapp.com). You might be surprised how much bandwisdth you
```suggestion
Smaller images mean faster downloads for your users. This is a lovely "set and forget" tool from the lovely folks at [Calibre](https://calibreapp.com). You might be surprised how much bandwidth you save.
```

2024-05-26 14:03 UTC, andycroll commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Additionally this is only for image assets included in your application or site. Any user uploaded images will need resizing and compressing using an alternative technique. I’ve had great experience
```suggestion
Note that this is only for image assets included in your application or site. Any user-uploaded images will need resizing and compressing using an alternative technique. I’ve had great experience with [imgproxy](https://imgproxy.net) at CoverageBook.
```

2024-05-27 14:29 UTC, nodunayo requested changes

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +description: "Using a set and forget Github Action"
*set-and-forget (?)

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +description: "Using a set and forget Github Action"
*GitHub

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Images can form a large proportion of the total download size of pages in your Rails application.
```suggestion
Images typically form a large proportion of the total download size of pages in your Rails application.
```

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Given that many image formats (both lossy and lossless) can be compressed further without visual regressions it makes sense to optimize them as much as you can without losing any visual fidelity.
```suggestion
Given that many image formats (both lossy and lossless) can be compressed further without any visual regression, it makes sense to optimize them up until that point.
```

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Add the following `.github/workflows/compress-images.yml` to your repository.
```suggestion
Add the following to your repository:
```

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +name: Optimize Images
```suggestion
# .github/workflows/compress-images.yml 

name: Optimize Images
```

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Smaller images mean faster downloads for your users. This is a lovely "set and forget" tool from the lovely folks at [Calibre](https://calibreapp.com). You might be surprised how much bandwidth you s
```suggestion
Smaller images mean faster downloads for your users. This is a great set-and-forget tool from the lovely folks at [Calibre](https://calibreapp.com). You might be surprised how much bandwidth you save.
```

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +This works for any repository, not just Rails applications. I use it on the [jekyll](https://jekyllrb.com) site you’re currently reading.
*Jekyll

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Maybe you dislike free performance improvements for you users? I kid. A bit.
```suggestion
Maybe you dislike free performance improvements for you users?

I kid.

A bit.
```

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +There’s still some human intervention needed to to make a good initial format decision for your imagery. You‘ll want to use the correct kind of format for the correct kind of image e.g. JPGs or WEBP
The 'e.g.' needs a little reworking so that what you're saying about JPGs & WEBPs vs PNGs is clearer.

2024-05-27 14:29 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Note that this is only for image assets included in your application or site. Any user-uploaded images will need resizing and compressing using an alternative technique. I’ve had great experience wit
*a great experience...

2024-05-27 20:30 UTC, andycroll commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +description: "Using a set and forget Github Action"
```suggestion
description: "Using a set-and-forget GitHub Action"
```

2024-05-27 20:33 UTC, andycroll commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +This works for any repository, not just Rails applications. I use it on the [jekyll](https://jekyllrb.com) site you’re currently reading.
```suggestion
This works for any repository, not just Rails applications. I use it on the [Jekyll](https://jekyllrb.com) site you’re currently reading.
```

2024-05-27 20:34 UTC, andycroll commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Note that this is only for image assets included in your application or site. Any user-uploaded images will need resizing and compressing using an alternative technique. I’ve had great experience wit
```suggestion
Note that this is only for image assets included in your application or site. Any user-uploaded images will need resizing and compressing using an alternative technique. I’ve had a great experience with [imgproxy](https://imgproxy.net) at CoverageBook.
```

2024-05-27 20:35 UTC, andycroll commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +There’s still some human intervention needed to to make a good initial format decision for your imagery. You‘ll want to use the correct kind of format for the correct kind of image e.g. JPGs or WEBP
```suggestion
There’s still some human intervention needed to to make a good initial format decision for your imagery. You‘ll want to use the correct file type for the image e.g. JPGs or WEBP offer better compression for photographic images.
```

2024-05-28 07:00 UTC, nodunayo requested changes, later dismissed

2024-05-28 07:00 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Maybe you dislike free performance improvements for you users?
*your

2024-05-28 07:00 UTC, nodunayo commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +There’s still some human intervention needed to to make a good initial format decision for your imagery. You‘ll want to use the correct file type for the image e.g. JPGs or WEBP offer better compress
*to

2024-05-28 07:02 UTC, andycroll commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +Maybe you dislike free performance improvements for you users?
```suggestion
Maybe you dislike free performance improvements for your users?
```

2024-05-28 07:03 UTC, andycroll commented on _posts/2024/2024-05-27-compress-your-images-using-github-actions.md
> +There’s still some human intervention needed to to make a good initial format decision for your imagery. You‘ll want to use the correct file type for the image e.g. JPGs or WEBP offer better compress
```suggestion
There’s still some human intervention needed to make a good initial format decision for your imagery. You‘ll want to use the correct file type for the image e.g. JPGs or WEBP offer better compression for photographic images.
```

2024-06-05 08:53 UTC, merged