present & blank
andycroll/andycroll.com pull request #214
Opened 2024-11-02 17:55 UTC by andycroll

2024-11-03 20:58 UTC, nodunayo requested changes, later dismissed

2024-11-03 20:58 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +When working with Rails, you often need to check if a value is effectively empty or if it contains meaningful data. Rails provides two very useful methods that are mixed into all objects, via Active
```suggestion
When working with Rails, you often need to check if a value contains meaningful data or is effectively empty. Rails, for this very purpose, provides, via Active Support, two very useful methods that are mixed into all objects: `blank?` and `present?`.
```

2024-11-03 20:58 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +...Rails' `blank?` and `present?` methods:
*Rails's (because singular)

2024-11-03 20:58 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +The `blank?` and `present?` methods, consolidate multiple checks into a single, readable method call. Your code becomes more expressive and easier to understand at a glance.
```suggestion
The `blank?` and `present?` methods consolidate multiple checks into a single, readable method call. Your code becomes more expressive and easier to understand at a glance.
```

2024-11-03 20:58 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +These methods are part of Active Support Core Extensions and thus work consistently across different types of objects (strings, arrays, hashes, etc.). They correctly handle cases like strings with on
```suggestion
These methods are part of Active Support Core Extensions and thus work consistently across different types of objects (strings, arrays, hashes, etc.). They correctly handle cases such as strings containing only whitespace, which a simple `empty?` check would incorrectly classify as having meaningful data/content. (??)
```

2024-11-03 20:58 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +For extremely performance-critical code, using `blank?` might be slightly slower than a direct `nil?` or `empty?` checks, as it performs multiple checks internally. But your milage may vary and you s
*than a direct nil or empty _check_

2024-11-03 20:58 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +For extremely performance-critical code, using `blank?` might be slightly slower than a direct `nil?` or `empty?` checks, as it performs multiple checks internally. But your milage may vary and you s
*mileage

2024-11-03 20:58 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +For the vast majority of Rails applications, using `blank?` and `present?` leads to cleaner, more idiomatic, and more maintainable code. There's a further enhancement [`presence` that can also make y
```suggestion
For the vast majority of Rails applications, using `blank?` and `present?` leads to cleaner, more idiomatic, and more maintainable code. For a further enhancement, check out [`presence`](/ruby/use-the-presence-method). Use of this method can also make your code more expressive.
```

2024-11-06 14:46 UTC, andycroll commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +...Rails' `blank?` and `present?` methods:
```suggestion
...Rails’s `blank?` and `present?` methods:
```

2024-11-06 14:49 UTC, andycroll commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +For extremely performance-critical code, using `blank?` might be slightly slower than a direct `nil?` or `empty?` checks, as it performs multiple checks internally. But your milage may vary and you s
```suggestion
For extremely performance-critical code, using `blank?` might be slightly slower than a direct `nil?` or `empty?` check, as it performs multiple methods internally. But your mileage may vary and you should benchmark to determine if this is a concern for your specific usage.
```

2024-11-09 12:36 UTC, nodunayo reviewed
Great improvements!!

2024-11-09 12:36 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +When working with Rails, you often need to check if a value contains meaningful data or is effectively empty. Rails, for this very purpose, provides, via Active Support, two very useful methods that
*of _if_ it is effectively...

2024-11-09 12:36 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +These methods are part of Active Support Core Extensions and thus work consistently across different types of objects (strings, arrays, hashes, etc.). They correctly handle cases such as strings cont
Hyperlink to ASCE docs?

2024-11-09 12:36 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +For extremely performance-critical code, using `blank?` might be slightly slower than a direct `nil?` or `empty?` check, as it can use multiple methods internally. But your mileage may vary and you s
*as it uses multiple methods internally

Unless it depends on the object type, which it probably does..! So ignore me if it's literally "sometimes it uses multiple methods but not always".

2024-11-09 12:36 UTC, nodunayo commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +For the vast majority of Rails applications, using `blank?` and `present?` leads to cleaner, more idiomatic, and more maintainable code. For a further enhancement, check out [`presence`](/ruby/use-th
*, which can also make your code more expressive.

2024-11-10 21:24 UTC, andycroll commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +For the vast majority of Rails applications, using `blank?` and `present?` leads to cleaner, more idiomatic, and more maintainable code. For a further enhancement, check out [`presence`](/ruby/use-th
```suggestion
For the vast majority of Rails applications, using `blank?` and `present?` leads to cleaner, more idiomatic, and more maintainable code. For a further enhancement, check out [`presence`](/ruby/use-the-presence-method), which can also make your code more expressive.
```

2024-11-10 21:25 UTC, andycroll commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +When working with Rails, you often need to check if a value contains meaningful data or is effectively empty. Rails, for this very purpose, provides, via Active Support, two very useful methods that
```suggestion
When working with Rails, you often need to check if a value contains meaningful data or if it is effectively empty. Rails, for this very purpose, provides, via Active Support, two very useful methods that are mixed into all objects: `blank?` and `present?`.
```

2024-11-10 21:26 UTC, andycroll commented on _posts/2024/2024-11-11-use-blank-and-present-in-rails.md
> +These methods are part of Active Support Core Extensions and thus work consistently across different types of objects (strings, arrays, hashes, etc.). They correctly handle cases such as strings cont
```suggestion
These methods are part of [Active Support's Core Extensions](https://guides.rubyonrails.org/active_support_core_extensions.html) and thus work consistently across different types of objects (strings, arrays, hashes, etc.). They correctly handle cases such as strings containing only whitespace, which a simple `empty?` check would incorrectly classify as having meaningful content.
```

2024-11-10 21:28 UTC, merged